/* Appel de mutation direct */
export default {
  SET_DOWN: 'setDown',
  SET_UP: 'setUp',
  SET_CONTACTS: 'setContacts',
  SET_DOCS: 'setDocs',
  SET_CONTACTS_SEARCH: 'setContactsSearch',
  SET_NEWS: 'setNews',
  SET_USERS: 'setUsers',
  SET_NEWS_SEARCH: 'setNewsSearch',
  SHOW_NEWS_FILTER_DIALOG: 'showNewsFilterDialog',
  TOGGLE_NEWS_FILTER_DIALOG: 'toggleNewsFilterDialog',
  UPDATE_FILTERED_CONTACTS: 'updateFilteredContacts',
  UPDATE_FILTERED_NEWS: 'updateFilteredNews',
  SHOW_MORE_CONTACTS: 'showMoreContacts',
  SHOW_MORE_NEWS: 'showMoreNews',
  SET_WEATHER: 'setWeather',
  LOGIN: 'login',
  LOGOUT: 'logout',
  LOGIN_FAIL: 'loginFail',
  LOGIN_SUCCESS: 'loginSuccess',
  SHOW_LOGIN_DIALOG: 'showLoginDialog',
  LOG_ERROR_ON_CLIENT: 'logErrorOnClient',
  SHOW_ERROR_DIALOG: 'showErrorDialog',
  SHOW_DOWN_DIALOG: 'showDownDialog',
  HIDE_SEARCH: 'hideSearch',
  SHOW_OFFLINE_DIALOG: 'showOfflineDialog',
  LOGIN_WAITING: 'loginWaiting',
  LOGIN_STOP: 'loginStop',
  SHOW_CONTACTS_DIALOG: 'showContactsDialog',
  SHOW_CONTACTS_SNACKBAR: 'showContactsSnackbar',
  SET_PREFS: 'setPrefs',
  DELETE_USER_SUCCESS: 'deleteUserSuccess',
  DELETE_USER_ERROR: 'deleteUserError',
  SHOW_SHIFT_DIALOG: 'showShiftDialog'
}
