/* Action sur un évenement */
export default {
  HEALTHCHECK: 'healthcheck',
  LOAD_DATA: 'loadData',
  LOAD_CONTACTS: 'loadContacts',
  LOAD_USERS: 'loadUsers',
  LOAD_DOCS: 'loadDocs',
  LOAD_NEWS: 'loadNews',
  LOAD_BIM: 'loadBim',
  LOAD_WEATHER: 'loadWeather',
  UPDATE_FILTERED_CONTACTS: 'updateFilteredContacts',
  UPDATE_FILTERED_NEWS: 'updateFilteredNews',
  LOGIN: 'login',
  AUTO_LOGIN: 'autoLogin',
  LOGOUT: 'logout',
  LOGIN_SUCCESS: 'loginSuccess',
  LOGIN_FAILURE: 'loginFailure',
  LOGIN_WAITING: 'loginWaiting',
  LOGIN_STOP: 'loginStop',
  LOAD_PREFS: 'loadPrefs',
  SAVE_PREFS: 'savePrefs',
  IS_ADMIN: 'isAdmin',
  GET_ROLES: 'getRoles',
  DELETE_USER: 'deleteUser',
  SAVE_SHIFT: 'saveShift',
  LOAD_SHIFTS: 'loadShifts',
  DELETE_SHIFT: 'deleteShifts',
  DELETE_DETAILS: 'deleteDetails',
  EXTRACT_ALL: 'extractAll',
  GET_CHILDREN: 'getChildren',
  GET_CONTACT: 'getContact'
}
